import pytest
from openatoms.core import Matter, Container, Phase
from openatoms.actions import Move, Transform, Combine
from openatoms.dag import ProtocolGraph

# --- FIXTURES (Setting up the lab for each test) ---
@pytest.fixture
def basic_lab():
    source = Container("Source_Vessel", max_volume_ml=1000, max_temp_c=120)
    dest = Container("Dest_Vessel", max_volume_ml=50, max_temp_c=80) # Notice the small 50mL limit

    # Add 500mL of water to the source
    water = Matter("H2O", Phase.LIQUID, mass_g=500, volume_ml=500, temp_c=20)
    source.contents.append(water)

    return source, dest

# --- TEST SUITE 1: THE HALLUCINATION CATCHERS ---

def test_linter_catches_overflow(basic_lab):
    """Simulates an AI trying to overfill a container."""
    source, dest = basic_lab
    graph = ProtocolGraph("Test_Overflow")

    # AI tries to move 100mL into a 50mL container
    graph.add_step(Move(source=source, destination=dest, amount_ml=100))

    # The Linter should catch this and return False
    assert graph.dry_run() is False
    assert graph.is_compiled is False

def test_linter_catches_thermodynamic_violation(basic_lab):
    """Simulates an AI trying to melt a plastic container."""
    source, dest = basic_lab
    graph = ProtocolGraph("Test_Meltdown")

    # AI tries to heat a container with an 80C limit to 250C
    graph.add_step(Transform(target=dest, parameter="temperature_c", target_value=250.0, duration_s=300))

    # The Linter should catch the fire hazard
    assert graph.dry_run() is False

def test_linter_catches_empty_combination(basic_lab):
    """Simulates an AI trying to mix an empty beaker."""
    _, dest = basic_lab # Dest is empty
    graph = ProtocolGraph("Test_Empty_Mix")

    graph.add_step(Combine(target=dest, method="vortex", duration_s=30))

    assert graph.dry_run() is False

# --- TEST SUITE 2: THE HAPPY PATH (UNIVERSALITY) ---

def test_successful_compilation(basic_lab):
    """Simulates a perfectly valid protocol generated by an AI."""
    source, dest = basic_lab
    graph = ProtocolGraph("Test_Valid_Run")

    # AI moves a safe amount (40mL) into the 50mL container, then heats it safely to 60C
    graph.add_step(Move(source=source, destination=dest, amount_ml=40))
    graph.add_step(Transform(target=dest, parameter="temperature_c", target_value=60.0, duration_s=120))

    # The Linter should pass this perfectly
    assert graph.dry_run() is True
    assert graph.is_compiled is True

    # Ensure the JSON payload actually generates
    payload = graph.export_json()
    assert "Test_Valid_Run" in payload
    assert "Move" in payload
    assert "Transform" in payload
