import pytest

from openatoms.actions import Combine, Move, Transform
from openatoms.core import Container, Matter, Phase
from openatoms.dag import ProtocolGraph
from openatoms.exceptions import (
    CapacityExceededError,
    CompatibilityViolationError,
    EmptyContainerError,
    OrderingViolationError,
    ThermodynamicViolationError,
)
from openatoms.profiles import CapabilityProfile


# --- FIXTURES (Setting up the lab for each test) ---
@pytest.fixture
def basic_lab():
    source = Container("Source_Vessel", max_volume_ml=1000, max_temp_c=120)
    dest = Container(
        "Dest_Vessel",
        max_volume_ml=50,
        max_temp_c=80,
    )  # Notice the small 50mL limit

    # Add 500mL of water to the source
    water = Matter("H2O", Phase.LIQUID, mass_g=500, volume_ml=500, temp_c=20)
    source.contents.append(water)

    return source, dest

# --- TEST SUITE 1: THE HALLUCINATION CATCHERS ---

def test_linter_catches_overflow(basic_lab):
    """Simulates an AI trying to overfill a container."""
    source, dest = basic_lab
    graph = ProtocolGraph("Test_Overflow")

    # AI tries to move 100mL into a 50mL container
    graph.add_step(Move(source=source, destination=dest, amount_ml=100))

    # The linter should raise a structured physical constraint error.
    with pytest.raises(CapacityExceededError):
        graph.dry_run()
    assert graph.is_compiled is False
    assert source.current_volume == 500
    assert dest.current_volume == 0

def test_linter_catches_thermodynamic_violation(basic_lab):
    """Simulates an AI trying to melt a plastic container."""
    _, dest = basic_lab
    graph = ProtocolGraph("Test_Meltdown")

    # AI tries to heat a container with an 80C limit to 250C
    graph.add_step(
        Transform(
            target=dest,
            parameter="temperature_c",
            target_value=250.0,
            duration_s=300,
        )
    )

    # The linter should catch the thermal safety violation.
    with pytest.raises(ThermodynamicViolationError):
        graph.dry_run()
    assert graph.is_compiled is False

def test_linter_catches_empty_combination(basic_lab):
    """Simulates an AI trying to mix an empty beaker."""
    _, dest = basic_lab  # Dest is empty
    graph = ProtocolGraph("Test_Empty_Mix")

    graph.add_step(Combine(target=dest, method="vortex", duration_s=30))

    with pytest.raises(EmptyContainerError):
        graph.dry_run()
    assert graph.is_compiled is False

def test_dry_run_rolls_back_state_on_physics_error(basic_lab):
    """Ensures failed dry runs restore all containers to pre-run state."""
    source, dest = basic_lab
    graph = ProtocolGraph("Test_Rollback")

    graph.add_step(Move(source=source, destination=dest, amount_ml=20))
    graph.add_step(
        Transform(target=dest, parameter="temperature_c", target_value=250.0, duration_s=60)
    )

    with pytest.raises(ThermodynamicViolationError):
        graph.dry_run()

    assert graph.is_compiled is False
    assert source.current_volume == 500
    assert dest.current_volume == 0
    assert len(dest.contents) == 0
    assert source.contents[0].temp_c == 20

# --- TEST SUITE 2: THE HAPPY PATH (UNIVERSALITY) ---

def test_successful_compilation(basic_lab):
    """Simulates a perfectly valid protocol generated by an AI."""
    source, dest = basic_lab
    graph = ProtocolGraph("Test_Valid_Run")

    # AI moves a safe amount (40mL) into the 50mL container, then heats it safely to 60C
    graph.add_step(Move(source=source, destination=dest, amount_ml=40))
    graph.add_step(
        Transform(
            target=dest,
            parameter="temperature_c",
            target_value=60.0,
            duration_s=120,
        )
    )

    # The Linter should pass this perfectly
    assert graph.dry_run() is True
    assert graph.is_compiled is True

    # Ensure the JSON payload actually generates
    payload = graph.export_json()
    assert "Test_Valid_Run" in payload
    assert "Move" in payload
    assert "Transform" in payload


def test_linter_catches_incompatible_hazard_transfer():
    source = Container("Source", max_volume_ml=100, max_temp_c=100)
    dest = Container(
        "Dest",
        max_volume_ml=100,
        max_temp_c=100,
        incompatible_hazards={"flammable"},
    )
    source.contents.append(
        Matter("Solvent", Phase.LIQUID, mass_g=50, volume_ml=20, hazard_class="flammable")
    )
    graph = ProtocolGraph("Hazard_Compatibility")
    graph.add_step(Move(source=source, destination=dest, amount_ml=5))

    with pytest.raises(CompatibilityViolationError):
        graph.dry_run()


def test_capability_profile_enforces_bounds():
    source = Container("Source", max_volume_ml=100, max_temp_c=100)
    dest = Container("Dest", max_volume_ml=100, max_temp_c=100)
    source.contents.append(Matter("H2O", Phase.LIQUID, mass_g=20, volume_ml=20))

    graph = ProtocolGraph("Capability_Bounds")
    graph.add_step(Move(source=source, destination=dest, amount_ml=10))

    profile = CapabilityProfile.from_iterables(
        name="small_target",
        allowed_actions=["Move"],
        max_move_ml=5,
    )
    with pytest.raises(OrderingViolationError):
        graph.dry_run(capability_profile=profile)
