"""Validation helpers for the BCI verification bottleneck example."""

from .derco_loader import compute_n400_d_prime, load_derco_n400
from .reference_data import (
    BCI_PRACTICAL_THRESHOLD_D_PRIME,
    BRIDGE_ITR_IMPROVEMENT_AT_LOW_D_PRIME,
    CROSSOVER_D_PRIME,
    CROSSOVER_TOLERANCE,
    D_PRIME_CONSUMER_EEG,
    D_PRIME_MIDRANGE_EEG,
    D_PRIME_RESEARCH_GRADE,
    GPT2_CHARACTER_ENTROPY_BITS,
    GPT2_SPEEDUP_FACTOR,
    GPT4_PROJECTED_ENTROPY_BITS,
    GPT4_PROJECTED_SPEEDUP,
    N400_ACTIVE_D_PRIME,
    N400_PASSIVE_D_PRIME,
    REPRODUCTION_TOLERANCE_FRACTION,
    UNIFORM_ENTROPY_BITS,
)

__all__ = [
    "BCI_PRACTICAL_THRESHOLD_D_PRIME",
    "BRIDGE_ITR_IMPROVEMENT_AT_LOW_D_PRIME",
    "CROSSOVER_D_PRIME",
    "CROSSOVER_TOLERANCE",
    "D_PRIME_CONSUMER_EEG",
    "D_PRIME_MIDRANGE_EEG",
    "D_PRIME_RESEARCH_GRADE",
    "GPT2_CHARACTER_ENTROPY_BITS",
    "GPT2_SPEEDUP_FACTOR",
    "GPT4_PROJECTED_ENTROPY_BITS",
    "GPT4_PROJECTED_SPEEDUP",
    "N400_ACTIVE_D_PRIME",
    "N400_PASSIVE_D_PRIME",
    "REPRODUCTION_TOLERANCE_FRACTION",
    "UNIFORM_ENTROPY_BITS",
    "compute_n400_d_prime",
    "load_derco_n400",
]
